adding kubevip service election
lablabs/ansible-role-rke2 pull request #192
Opened 2024-02-13 15:14 UTC by strelok899

# Description

adding kube vip service leader election 
https://kube-vip.io/docs/usage/kubernetes-services/#load-balancing-load-balancers-when-using-arp-mode-yes-you-read-that-correctly-kube-vip-v050

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [ ] Small minor change not affecting the Ansible Role code (Github Actions Workflow, Documentation etc.)

## How Has This Been Tested?
run on my internal clusters with successes

2024-02-22 16:16 UTC, MonolithProjects requested changes

2024-02-22 16:16 UTC, MonolithProjects commented on defaults/main.yml
> +# To circumvent this kube-vip has implemented a new function which is "leader election per service",
Please remove the trailing white space on the end of this line. Thanks
https://github.com/lablabs/ansible-role-rke2/actions/runs/7888640859/job/21870718938?pr=192

2024-02-22 16:16 UTC, MonolithProjects commented on README.md
> +# To circumvent this kube-vip has implemented a new function which is "leader election per service",
Please remove the trailing white space from this line. Thanks
https://github.com/lablabs/ansible-role-rke2/actions/runs/7888640859/job/21870718938?pr=192

2024-02-29 07:16 UTC, strelok899 commented
@MonolithProjects done

2024-02-29 21:26 UTC, MonolithProjects approved these changes
LGTM

2024-02-29 21:27 UTC, merged