adding option to disable builtin cloud controller
lablabs/ansible-role-rke2 pull request #202
Opened 2024-03-06 17:56 UTC by strelok899

# Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [ ] Small minor change not affecting the Ansible Role code (GitHub Actions Workflow, Documentation etc.)

## How Has This Been Tested?

2024-03-14 19:56 UTC, MonolithProjects requested changes
Hi, could you please fix trailing whitespaces? The rest looks fine to me. https://github.com/lablabs/ansible-role-rke2/actions/runs/8178960201/job/22516426622?pr=202

2024-03-18 12:27 UTC, strelok899 commented
@MonolithProjects done

2024-03-18 14:56 UTC, MonolithProjects approved these changes
LGTM. Thanks

2024-03-18 14:57 UTC, merged

2024-04-08 06:55 UTC, mueller-ma commented on README.md
> +rke2_cloud_provider_name: "rke2"
According to the comment above `rke2` isn't a valid argument. `defaults/main.yml` uses `external.`