Add partition check for /usr/local
lablabs/ansible-role-rke2 pull request #213
Opened 2024-05-07 13:38 UTC by jLemmings

# Description

The initial PR only solved the issue if /usr/local is not writeable. The RKE2 install scripts also checks if /usr/local is a separate partition which was not checked by the role before. This PR adds the partition check.
Issue: https://github.com/lablabs/ansible-role-rke2/issues/193

## Type of change

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Small minor change not affecting the Ansible Role code (GitHub Actions Workflow, Documentation etc.)

## How Has This Been Tested?
This has been tested in own airgapped environment on RHEL9, ansible-role-rke2 version 1.33.0 and RKE2 v1.26.11+rke2r1

2024-05-10 12:53 UTC, MonolithProjects requested changes

2024-05-13 05:26 UTC, jLemmings commented on tasks/cis.yml
> +  command: grep '/usr/local ' /proc/mounts
Updated the PR :)

2024-05-13 16:35 UTC, MonolithProjects approved these changes
LGTM. Thanks!

2024-05-14 05:46 UTC, merged

2024-05-17 22:15 UTC, Evantage-WS commented
@jLemmings, sorry to say, but the new code is still failing....

```
 clusterx-m1: fatal: [192.168.1.2]: FAILED! => {"changed": false, "cmd": ["grep", "/usr/local ", "/proc/mounts"], "delta": "0:00:00.001180", "end": "2024-05-18 00:06:28.515536", "msg": "non-zero return code", "rc": 1, "start": "2024-05-18 00:06:28.514356", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

I have changed some code in rke2.yaml:
```
- name: Set RKE2 path set default paths
  ansible.builtin.set_fact:
    rke2_bin_path: "/usr/local/bin/rke2"
    rke2_share_path: "/usr/local/bin/rke2"

- name: Set RKE2 path (overrule when /usr/local is not writeable or /usr/local is a mountpoint)
  ansible.builtin.set_fact:
    rke2_bin_path: "/opt/rke2/bin/rke2"
    rke2_share_path: "/opt/rke2/share/rke2"
  when: usr_local.stat.writeable == False or volume_stat.rc == 0 | default(false)
```
and also the cis.yaml file needs a change:
```
- name: Copy systemctl config file for kernel hardening
  ansible.builtin.copy:
    src: "{{ rke2_share_path }}/rke2-cis-sysctl.conf"
    dest: /etc/sysctl.d/60-rke2-cis.conf
    mode: 0600
    remote_src: true
  notify: Restart systemd-sysctl
```