feat: add configuation option for cluster-domain
lablabs/ansible-role-rke2 pull request #232
Opened 2024-06-11 02:15 UTC by CrimsonFez

# Description
I added an option to specify the cluster domain and updated the documentation for the change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Small minor change not affecting the Ansible Role code (GitHub Actions Workflow, Documentation etc.)

## How Has This Been Tested?
I haven't been able to get the molecule tests to work because I'm using podman instead of docker. If this is an issue please let me know.

2024-06-12 20:14 UTC, MonolithProjects approved these changes

2024-06-12 20:18 UTC, MonolithProjects requested changes
Please update the Readme file with new variable. Thanks

2024-06-12 20:51 UTC, CrimsonFez commented
Anything else?

2024-06-13 05:05 UTC, MonolithProjects approved these changes
LGTM

2024-06-13 07:37 UTC, merged