tighten permissions
lablabs/ansible-role-rke2 pull request #266
Opened 2024-10-13 16:37 UTC by simonfelding

# Description

This tightens security a bit.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Small minor change not affecting the Ansible Role code (GitHub Actions Workflow, Documentation etc.)

## How Has This Been Tested?
it works fine

2024-10-27 20:53 UTC, MonolithProjects requested changes

2024-10-27 20:53 UTC, MonolithProjects commented on tasks/first_server.yml
> +    mode: 0750
Modifying file and directory permissions to differ from those in the upstream RKE2 installation is not within the scope of this Ansible Role.

2024-10-27 20:53 UTC, MonolithProjects commented on tasks/ingress-nginx.yml
> +    mode: 0660
Modifying file and directory permissions to differ from those in the upstream RKE2 installation is not within the scope of this Ansible Role.

2024-10-27 20:53 UTC, MonolithProjects commented on tasks/remaining_nodes.yml
> +    mode: 0750
Modifying file and directory permissions to differ from those in the upstream RKE2 installation is not within the scope of this Ansible Role.

2024-10-27 20:53 UTC, MonolithProjects commented on tasks/standalone.yml
> +    mode: 0750
Modifying file and directory permissions to differ from those in the upstream RKE2 installation is not within the scope of this Ansible Role.

2024-10-29 11:38 UTC, simonfelding commented
ok makes sense

2024-10-29 11:38 UTC, closed without merging